# Generated by Django 4.1 on 2022-08-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_desc', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('image', models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/')),
            ],
        ),
    ]
